services:
  nextcloud-redis:
    image: redis:7-alpine
    container_name: nextcloud-redis
    networks:
      - appnet
    restart: unless-stopped

  nextcloud:
    image: nextcloud:29-apache
    container_name: nextcloud
    expose:
      - "80"
    environment:
      # PostgreSQL 설정 (기존 pg-local 컨테이너 사용)
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      
      # Redis 설정 (성능 향상)
      REDIS_HOST: ${REDIS_HOST}
      REDIS_HOST_PORT: ${REDIS_HOST_PORT:-6379}
      
      # NextCloud 설정
      NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
      NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}
      NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_TRUSTED_DOMAINS}
      
      # Nginx 프록시 설정
      OVERWRITEPROTOCOL: ${OVERWRITEPROTOCOL:-https}
      OVERWRITEHOST: ${OVERWRITEHOST}
      OVERWRITECLIURL: ${OVERWRITECLIURL}
      OVERWRITEWEBROOT: ${OVERWRITEWEBROOT:-}
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-172.16.0.0/12}
      
      TZ: ${TZ:-Asia/Seoul}
    
    volumes:
      - nextcloud-data:/var/www/html
      # 로컬 파일 저장소 (선택사항 - 호스트와 동기화하려면)
      # - ./nextcloud-files:/var/www/html/data
    
    depends_on:
      - nextcloud-redis
    
    networks:
      - appnet
      - nginx-network
    
    restart: unless-stopped

networks:
  appnet:
    external: true
  nginx-network:
    external: true
    name: nginx-network

volumes:
  nextcloud-data:
    name: nextcloud-data

